from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    company_name: Annotated[str, "Resolved human-readable company/fund name"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # quant score (deterministic factor scoring after analysts, before macro_context)
    quant_score: Annotated[
        str, "Quant factor score report (momentum/value/quality/growth/lowvol/anticrowding), 0-100 composite + breakdown"
    ]

    # capital flow (deterministic capital flow regime + score, runs after market_analyst, before quant_score)
    capital_flow_yaml: Annotated[
        str, "Capital flow YAML: DDX/DDY/DDZ-like, northbound, holder number, regime, capital_flow_score"
    ]
    capital_flow_report: Annotated[
        str, "Capital flow markdown report (capital_flow.md)"
    ]
    capital_flow_metrics: Annotated[
        dict, "Capital flow structured metrics dict (full descriptive field names, consumed by quant_score & RM)"
    ]

    # macro context (synthesized after analysts, before stock_profile)
    macro_context: Annotated[
        str, "Macro context: rate cycle stage, liquidity tightness, geopolitical risk, sector relative impact"
    ]

    # stock profile (synthesized after macro_context, drives downstream report weighting and decision style)
    stock_profile: Annotated[
        str, "Stock profile: market cap tier, style, liquidity, instrument type, report weights, decision style, event windows"
    ]

    # sector comparison (after stock_profile: RS vs market/industry/theme ETFs + theme peers)
    sector_comparison: Annotated[
        str, "Sector RS report: relative strength vs 大盘三档 + 行业 ETF + 主题 ETF + 主题代表股"
    ]

    # consensus snapshot (synthesized after all analysts, before bull/bear)
    consensus_snapshot: Annotated[
        str, "Market consensus snapshot: priced-in expectations, narrative, unknowns"
    ]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]  # DEPRECATED in optimization 05: Trader node removed, kept for backward compat

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
